### ISSUE TITLE
fix(be): service fails if too many epochs are downloaded at once

### ISSUE THREAD

**Issue by bogdan-manole** [input-output-hk/constitution-checker#104]
## Description
If you start the service for the first time it will not be able to fetch too many epochs

## Acceptance Criteria

- [ ] no matter how many epochs have to be fetched, the service should handle it
- [ ] propagate the thread failing to the main process, and exit the process with an error code

**Comment by RSoulatIOHK** [comment]
Seems like a pretty serious bug to fix if we want to hand the project to another team.
Should we plan it for next sprint?

**Comment by bogdan-manole** [comment]
the issue with the epochs is that some older epochs don't provide values for all the parameters (through blockfrost).
I just bumped the historical starting point of the parameter epochs download, and we can find the proper way to mitigate such a scenario later.
