### ISSUE TITLE
Quick & Dirty HTMX Front end

### ISSUE THREAD

**Issue by RSoulatIOHK** [input-output-hk/constitution-checker#32]
## Description
HTMX FE so that people can demo the tool or experiment with it

## Acceptance Criteria

- [ ] Can upload a JSON file
- [ ] Can fill the form
- [ ] Get all the check results in the FE

## Acceptance criteria secondary list
- [ ] Can download the output JSON

**Comment by robpangilinanioi** [comment]
relates to https://github.com/input-output-hk/constitution-checker/issues/11
