### ISSUE TITLE
Add the possibility to have someone specify a Transaction ID on SanchoNet

### ISSUE THREAD

**Issue by RSoulatIOHK** [input-output-hk/constitution-checker#61]

**Comment by robpangilinanioi** [comment]
Need to have discussions with @bogdan-manole

**Comment by KJES4** [comment]
Blocked, waiting for the new route before I can do the FE part.

**Comment by robpangilinanioi** [comment]
@bogdan-manole FYI on this item.  Need to deploy the dependent item for this to move.

**Comment by KJES4** [comment]
PR created https://github.com/input-output-hk/constitution-checker/pull/79
