### ISSUE TITLE
Add the possibility to have someone specify a URL with a JSON of a proposal

### ISSUE THREAD

**Issue by RSoulatIOHK** [input-output-hk/constitution-checker#62]

**Comment by KJES4** [comment]
The form is there to capture the URL, just need to sync with BE to see there needs to be any preprocessing done on the FE before the URL string is sent to BE. I've sent a message already to ask about this.

**Comment by robpangilinanioi** [comment]
@EehMauro are you able to help review this?  thanks

**Comment by robpangilinanioi** [comment]
@KJES4 will support the feedback provided by @EehMauro in the review process and it should be done.
