### ISSUE TITLE
Write tests for the FE

### ISSUE THREAD

**Issue by KJES4** [input-output-hk/constitution-checker#81]
- [x] Set up Zustand store to handle tests properly 
- [x] Create mock data 
- [x] Write unit and integration tests for all components
- [x] Set up code coverage report to work in the CLI and to show in the repo

**Comment by KJES4** [comment]
Created PR https://github.com/input-output-hk/constitution-checker/pull/83

**Comment by robpangilinanioi** [comment]
Moving to Sprint 3 just for the PR - review process.
