### ISSUE TITLE
Architecture document

### ISSUE THREAD

**Issue by RSoulatIOHK** [input-output-hk/constitution-checker#9]
## Description
Architecture of the doc based on the Epic A/C
Content:

- Architecture of the Backend so that FE can get the necessary information
- Explanation of the architecture so that people can contribute to the repo
- How can someone contribute with new checks:
   - What they can expect from the context
   - How they need to format their output

## Acceptance Criteria

- [ ] Architecture doc on an `ARCHITECTURE.md` on the repo

**Comment by robpangilinanioi** [comment]
@RSoulatIOHK @bogdan-manole what milestone / pi objective is this tied to?  thanks

**Comment by robpangilinanioi** [comment]
This is put back to To Do because there are pre-requisite items for it.

**Comment by robpangilinanioi** [comment]
relates to this https://github.com/input-output-hk/constitution-checker/issues/11

**Comment by RSoulatIOHK** [comment]
Reviewed
